
default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV.fetch("POSTGRES_DB") { "askme" } %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "<%= ENV.fetch("POSTGRES_USER") { "user_askme" } %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") { "1234" } %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "askme" } %>_development


test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "askme" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "askme" } %>_production