
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user_askme
  password: 1234
  host: localhost
  port: 5432
  

development:
  <<: *default
  database: askme_development


test:
  <<: *default
  database: askme_test

production:
  <<: *default
  database: askme_production
